### ISSUE TITLE
task_attempt api not working

### ISSUE THREAD

**Issue by Williej926** [toidi/hadoop-yarn-api-python-client#10]
> path = '/ws/v1/history/mapreduce/jobs/{jobid}/tasks/{taskid}/attempt/{attemptid}'.format(
>             jobid=job_id, taskid=task_id, attemptid=attempt_id)

it should be "attempts" in the path

**Comment by dimon222** [comment]
No longer the case. Seems like the code is already fixed in 1806ff7ad423097cf3c791e8067ae7444862c827
