### ISSUE TITLE
Response 401 - How do we pass authentication

### ISSUE THREAD

**Issue by klainn** [toidi/hadoop-yarn-api-python-client#12]
Is there functionality in your module to allow for authentication? 

My code is as such:

`from yarn_api_client import HistoryServer
yhs = HistoryServer("localhost")

print(yhs.application_information())
`

and my output is 

$ python yarn_resource_manager.py
Traceback (most recent call last):
  File "yarn_resource_manager.py", line 8, in <module>
    print(yhs.application_information())
  File "/home/username/sites/envs/hdpsnow/lib/python3.6/site-packages/yarn_api_client/history_server.py", line 29, in application_information
    return self.request(path)
  File "/home/username/sites/envs/hdpsnow/lib/python3.6/site-packages/yarn_api_client/base.py", line 41, in request
    raise APIError(msg)
yarn_api_client.errors.APIError: Response finished with status: 401

I looked through the docs and I don't see a way to pass a username/password/kerberos ticket.

**Comment by dimon222** [comment]
I assume this ticket can be closed?
Kerberos was added several versions back. requests_kerberos (which is used in this case) is using system's kerberos ticket for auth. You might have to figure out yourself some way for ticket refresh in cache (cron?), but thats it, and KerberosClient should do the rest of work.

**Comment by skadyan** [comment]
can we add the support for passing the kerberos principal name when enabling the kerberos authentication?

**Comment by dimon222** [comment]
@skadyan #34 is supposed to add more flexibility by letting user initialise AuthBase constructor, if it eventually gets merged - sure.
