### ISSUE TITLE
Add support for YARN with HTTPS endpoints

### ISSUE THREAD

**Issue by lresende** [toidi/hadoop-yarn-api-python-client#19]

**Comment by dimon222** [comment]
Options I see:  
1. Introduce breaking change, follow the path of libs like "hdfs" where you provide http/https in list of endpoints as prefix.   
2. Introduce boolean flag in constructors to switch to HTTPS in prefix in urls inside codebase itself. In this case breaking change not introduced, but the project is not conforming "general" style.

So far option 2 looks less intrusive, I'll prepare PR.
