### ISSUE TITLE
add submit applications api

### ISSUE THREAD

**Issue by lulualibaba** [toidi/hadoop-yarn-api-python-client#30]

**Comment by dimon222** [comment]
What do you mean?

**Comment by lulualibaba** [comment]
> What do you mean?

https://hadoop.apache.org/docs/r2.7.3/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html
POST http://<rm http address:port>/ws/v1/cluster/apps/new-application
why "Post" is not impl yet?
