### ISSUE TITLE
Simplify the current API support for host information

### ISSUE THREAD

**Issue by lresende** [toidi/hadoop-yarn-api-python-client#33]
Currently, the provided APIs have parameters for each piece of a endpoint e.g. ( address=None, port=8088, alt_address=None, alt_port=8088) and we are adding even more related to https, etc. 

I was wondering if it would make sense to introduce an endpoint parameter that would incorporate all these info

`service_endpoint`=`https://server:port`

Then, in the case where we need to decompose the endpoint into the specific pieces, we can easily use the code snipp below:

```
service_uri = Uri(service_endpoint)
self.scheme = service_uri.scheme or 'https'
self.hostname = service_uri.hostname
self.port = service_uri.port or '8088'
self.api_endpoint = service_uri.path or '/ws/v1/cluster'
```

**Comment by dimon222** [comment]
Makes sense. I would suggest make only one single parameter "endpoints" which would represents array of complete endpoint strings (like you mentioned). The necessary port, prefixes and other stuff can be accordingly cutted from result endpoints and decoupled (if needed, so far it seems - its not needed)

**Comment by kevin-bates** [comment]
I agree with this proposal - it a good thing.

Since this will force clients to update, should we create `0.3.4` from the currently merged PRas and expose this as `0.4.0`?  Not sure what "contract" we must honor prior to `1.0.0`.

**Comment by dimon222** [comment]
I believe this can be closed now (related PR is merged)

**Comment by kevin-bates** [comment]
+1 - Thanks for the ping - closing now.
